#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LGUI, TT(1), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_BSLS, KC_LALT, MO(1), KC_SPC, KC_ENT, MO(2), KC_MINS),
	[1] = LAYOUT(KC_GRV, KC_BTN1, KC_ACL0, KC_ACL1, KC_ACL2, KC_NO, KC_LPRN, KC_RPRN, KC_MINS, KC_EQL, KC_BSLS, KC_DEL, KC_INS, KC_BTN1, KC_MS_U, KC_BTN2, KC_WH_U, KC_LPRN, KC_RPRN, KC_PGUP, KC_UP, KC_PGDN, KC_PSCR, KC_INS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, KC_LCBR, KC_RCBR, KC_LEFT, KC_DOWN, KC_RGHT, KC_PLUS, KC_HOME, KC_LSFT, KC_HOME, KC_BTN3, KC_END, KC_MUTE, KC_LBRC, KC_MYCM, KC_TRNS, KC_RBRC, KC_HOME, KC_INS, KC_END, KC_MINS, KC_END, KC_LGUI, KC_TRNS, KC_SPC, KC_ENT, MO(3), KC_MINS),
	[2] = LAYOUT(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_FIND, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TRNS, KC_MUTE, KC_MPRV, KC_MNXT, KC_VOLU, KC_PGUP, KC_UNDS, BL_INC, RGB_SPI, RGB_HUI, RGB_SAI, RGB_MOD, RGB_VAI, KC_CALC, KC_MSTP, KC_MPLY, KC_VOLD, KC_PGDN, KC_MINS, KC_TRNS, KC_TRNS, BL_DEC, RGB_SPD, RGB_HUD, RGB_SAD, RGB_RMOD, RGB_VAD, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
};

// void encoder_update_user(uint8_t index, bool clockwise) {
//     if (index == 0) {
//         if (clockwise) {
//             tap_code(KC_VOLU);
//         } else {
//             tap_code(KC_VOLD);
//         }
//     }
//     else if (index == 1) {
//         if (clockwise) {
//             tap_code(KC_PGDN);
//         } else {
//             tap_code(KC_PGUP);
//         }
//     }
// }
